### ISSUE TITLE
Missing Google reCapture environment variable on Heroku deploying

### ISSUE THREAD

**Issue by fntsrlike** [fateyan/Slack-Inviter#4]
Missing Google reCapture environment variable on Heroku deploying. Fields need to be added by user-self. They should be generate by system

**Comment by fntsrlike** [comment]
You should also update `README.md`. =)

**Comment by fateyan** [comment]
OK, thanks for your remind.

updated at [815bcc1](https://github.com/fateyan/Slack-Inviter/commit/815bcc1bc9a690f515be401885b409e098add817)
