### ISSUE TITLE
After submit, it appear error page without any tips

### ISSUE THREAD

**Issue by fntsrlike** [fateyan/Slack-Inviter#5]
![2016-03-24 2 45 16](https://cloud.githubusercontent.com/assets/2680724/14010329/16f8631c-f1cf-11e5-9f38-2faa276f6a79.png)

Don't know what happened and what is wrong.

**Comment by fntsrlike** [comment]
It is due to `SLACK_DOMAIN` environment variable set wrong. I fill `XXXX.slack.com`, but program expect only `XXXX`.

**Comment by ghost** [comment]
This should be support, which can be improved a better user experience.
Take `soscet.slack.com`, for example, the program should use `rtrim` to remove the `.slack.com` follow by user's input.

**Comment by fateyan** [comment]
@BinotaLiu 's suggestion is pretty good.

I had added it at [2b56190](https://github.com/fateyan/Slack-Inviter/commit/2b561908addb232d2641be4116b3a4fc268d1033)
