### ISSUE TITLE
Channels instruction out of date

### ISSUE THREAD

**Issue by rickmills** [fateyan/Slack-Inviter#7]
The instructions for setting this up tell you to go to a specific url to get a list of channels (doesn't explain why, or what to do with them).

The link it references is a 404.

**Comment by fateyan** [comment]
Hello,
Thanks for your issue. 😉 

https://github.com/fateyan/Slack-Inviter/blob/master/app.json#L15
The slack API was changed, I'll fixed it.

I think it is what you want. 😄 
https://api.slack.com/methods/channels.list/test

Cheers
